# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
extra-source-files:
- package.yaml
- README.md
- stack.yaml
ghc-options:
- -Wall
library:
  dependencies:
  - base >=4 && <5
  - mtl
  - regex-pcre
  source-dirs: src
  exposed-modules:
  - Datum
  - DMS
  - ECEFRef
  - Ellipsoid
  - IrishRef
  - LatLng
  - MathExtensions
  - MGRSRef
  - OSRef
  - UTMRef
author: Daniele Francesconi
maintainer: dfrancesconi12@gmail.com
name: hcoord
synopsis: Easily convert between latitude/longitude, UTM and OSGB.
description: Please see README.md
homepage: https://github.com/danfran/hcoord#readme
category: geography
license: BSD3
license-file: LICENSE
copyright: copyleft
github: https://github.com/danfran/hcoord
executables:
  hcoord-exe:
    dependencies:
    - base
    - hcoord
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: app
tests:
  hcoord-test:
    dependencies:
    - base
    - HUnit >= 1.2 && < 1.6
    - hcoord
    - mtl
    - ieee754
    - data-default
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    main: Spec.hs
    source-dirs:
    - test
  hlint-test:
    dependencies:
    - base
    - hlint
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    main: HLint.hs
    source-dirs:
    - hlint
version: '1.0.0.0'
