resolver: lts-11.7
packages:
- build
- hcoord
- hcoord-utm
- hcoord-irish
- hcoord-mgrs
- hcoord-osgb
- location:
    git: https://github.com/brunjlar/stack2cabal
    commit: a8a4cdcacd697cee648af93856735f15de5987a6
  extra-dep: false
- location:
    git: https://github.com/haskell-CI/haskell-ci
    commit: 105005cde6bde903e477e5b9724d02bdea06bae4
  extra-dep: false
