# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
extra-source-files:
- package.yaml
- README.md
ghc-options:
- -Wall
library:
  dependencies:
  - base >=4 && <5
  - mtl
  - hcoord
  source-dirs: src
  exposed-modules:
  - OSRef
author: Daniele Francesconi
maintainer: dfrancesconi12@gmail.com
name: hcoord-osgb
synopsis: Short synopsis.
description: Longer description.
category: geography
license: BSD3
license-file: LICENSE
copyright: copyleft
github: danfran/hcoord
tested-with: GHC == 8.2.2
tests:
  hcoord-osgb-test:
    dependencies:
    - base >=4 && <5
    - HUnit
    - hcoord
    - mtl
    - ieee754
    - data-default
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    main: Spec.hs
    source-dirs:
    - test
    - src
  hlint-test:
    dependencies:
    - base >=4 && <5
    - hlint
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    main: HLint.hs
    source-dirs:
    - hlint
version: '2.0.0'
